### ISSUE TITLE
Generate Builds

### ISSUE THREAD

**Issue by tonyschuite** [hku-ect/NatNetOSCrecorder#18]
For testing purposes, can we generate Pre-Alpha builds for both OSX as well as Windows?

**Comment by sphaero** [comment]
There has been no release yet but nightly's available here:

https://pong.hku.nl/~buildbot/nightly/


win: https://pong.hku.nl/~buildbot/nightly/NatNetOSCrecorder_win_master_3325.zip
osx: https://pong.hku.nl/~buildbot/nightly/NatNetOSCrecorder_osx_3325.zip
linux: https://pong.hku.nl/~buildbot/nightly/NatNetOSCrecorder_linux_3325.zip
